### ISSUE TITLE
Dependency conflict with dissect.target

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect#23]
Currently `dissect` requires `dissect.ntfs==3.3` but `dissect.target` requires `dissect.ntfs>=3.4.dev,<4.0.dev`

This causes a `ResolutionImpossible` dependency conflict when installing with pip.

https://github.com/fox-it/dissect.target/blob/main/setup.py#L61
https://github.com/fox-it/dissect/blob/main/setup.py#L18

**Comment by pyrco** [comment]
The `dissect` package is only to be used when you want to run the latest stable set of dissect projects that work together. If you want to run development versions of the other projects, remove the `dissect` package first. Unfortunately due to the way python packaging and dependency resolution works it is not possible to cater to both use cases with a single package.
